[controller]
host = "http://localhost:8000/c"
AccessKey = "ox00000000"
SecrectKey = "0xffffffff"
[self]
judgeCapability = 4
name = "TestJudger"
[builtin]
"ax309.ucf" = "/usr/src/ax309.ucf"
"main.cmd" = "/usr/src/main.cmd"
"verilog.prj" = "/usr/src/verilog.prj"
"xc6slx9-2-ftg256.verilog.xst" = "/usr/src/xc6slx9-2-ftg256.verilog.xst"
[language]
cat = "/usr/bin/cat"
xst = "/usr/bin/xst"
ngdbuild = "/usr/bin/ngdbuild"
map = "/usr/bin/map"
par = "/usr/bin/par"
bitgen = "/usr/bin/bitgen"
impact = "/usr/bin/impact"
[fpga]
constraints = "ax309.ucf"
program = "main.cmd"
package = "xc6slx9-2-ftg256"
serial = [
    "0123456789ABCDEF0123456789ABCDEF",
]
[judger]
noSelfTestError = false
tmpdirBase = "/tmp/Heng_Client"
timeRatioTolerance = 5
defaultPidLimit = 64
defaultTimeRatio = 1
selfTestRound = 5
uid = 1999
gid = 1999
cacheUsr = false
cacheSpj = true
cacheInteractor = true
remoteFileCacheBytes = 536870912
